defaults:
  - base
  - _self_

experiment:
  name: md_finetune
  batch_size: 32
  sample_mode: time_batch
  learning_rate: 0.00001  # Lower learning rate for fine-tuning
  warm_start: weights/paper_weights.pth
  use_warm_start_conf: True
  num_gpus: 1  # Adjust based on your setup

data:
  md_trajectory_path: Tau5R2R3_backbone.npz  # Add your MD data path
