defaults:
  - finetune_ar
  - _self_

model:
  use_sequence_conditioning: True
  conditioning_method: cross_attention  # Options: cross_attention, concat, adain
  sequence_embed:
    embed_dim: 1280  # ESM-2 embedding dimension
    embedding_path: embeddings/p15PAF_idr_embeddings.txt  # Path to your text file
    embedding_format: txt  # New field to specify format 